### ISSUE TITLE
The default label should be "invalid" for hacktoberfest

### ISSUE THREAD

**Issue by jgrumboe** [andrewslotin/rummelsnuff#6]
https://github.com/andrewslotin/rummelsnuff/blob/d864e4520e36505877c2c46f286cc6d31c112836/main.go#L18

According to the FAQ the label "invalid" is the official one for spam PRs.

**Comment by BenjaminPrice** [comment]
From the [FAQ page](https://hacktoberfest.digitalocean.com/faq):

> As a maintainer, how should I handle spam pull requests?
> 
> We dislike seeing spam pull requests just as much as you, so please give them an `invalid` or `spam` label and close them. Pull requests that contain a label with the word invalid or spam won’t be counted toward Hacktoberfest.

`invalid` or `spam` are both acceptable to disqualify a PR.

**Comment by jgrumboe** [comment]
hmmm ... I must have overseen this.
Thanks
